<?php

namespace ResumeBundle\Repository;

/**
 * AssigmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssigmentRepository extends \Doctrine\ORM\EntityRepository
{
}
