<?php

namespace ResumeBundle\Repository;

/**
 * BasicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasicRepository extends \Doctrine\ORM\EntityRepository
{
}
