<?php

namespace ResumeBundle\Repository;

/**
 * InfotextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfotextRepository extends \Doctrine\ORM\EntityRepository
{
}
