<?php

namespace ResumeBundle\Repository;

/**
 * TeacherDirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherDirectorRepository extends \Doctrine\ORM\EntityRepository
{
}
