<?php

namespace ResumeBundle\Repository;

/**
 * TeacherFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherFileRepository extends \Doctrine\ORM\EntityRepository
{
}
