<?php

namespace ResumeBundle\Repository;

/**
 * TechnicianMidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicianMidRepository extends \Doctrine\ORM\EntityRepository
{
}
