<?php

namespace ResumeBundle\Repository;

/**
 * TechnicianTopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicianTopRepository extends \Doctrine\ORM\EntityRepository
{
}
