<?php

namespace ResumeBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByRole($role)
  {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('u')
      ->from('ResumeBundle:User', 'u')
      ->where('u.roles LIKE :roles')
      ->setParameter('roles', '%"'.$role.'"%');

    return $qb->getQuery()->getResult();
  }
}
